/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BlogShareDialog: typeof import('./src/components/dialog/BlogShareDialog.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTree: typeof import('element-plus/es')['ElTree']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FavateBtn: typeof import('./src/components/FavateBtn.vue')['default']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    MDPreview: typeof import('./src/components/MDPreview.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar/index.vue')['default']
    Preview: typeof import('./src/components/MindMap/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/theme-switch/index.vue')['default']
    TreeList: typeof import('./src/components/MindMap/TreeList.vue')['default']
    UMessageInput: typeof import('./src/components/UMessageInput.vue')['default']
  }
}
